services:
  springboot-app:
    build:
      args:
        - VERTEX_AI_SERVICE_KEY_FILENAME=${VERTEX_AI_SERVICE_KEY_FILENAME}
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    networks:
      - job-of-better

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "13000:80"
    env_file:
      - .env
    networks:
      - job-of-better

  mysql-server:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - job-of-better

networks:
  job-of-better:
